"""
Patterns that should never appear in commands generated by the AI.

These are commonly used in shell injection attacks.
"""

DANGEROUS_PATTERNS = {
    "&&",
    ";",
    "||",
    "|",
    "$(",
    "`",
    ">",
    ">>",
    "<",
}